name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: |
        TAG=elephantdev/simplemusic:$(date +%s)
        docker build . --file Dockerfile --tag $TAG
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Push the Docker image
      run: docker push $TAG
      env:
        TAG: ${{ env.TAG }}      
