name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the build
    tags:
      - v*   # Optional: Trigger on tags starting with "v"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/elephantdev/simplemusic:${{ github.run_number }}